backend:
  name: git-gateway
  branch: master
media_folder: static/images
public_folder: /images
collections:
  - name: home
    label: Home
    files:
      - name: home
        label: Home
        file: src/pages/index.md
        fields:
          - name: en
            widget: object
            label: English
            fields:
              - widget: string
                name: title
                label: Title
                required: true
                hint: The title of the page.
              - widget: list
                name: sections
                label: Sections
                required: false
                hint: Home page sections.
                types:
                  - name: contentblock
                    widget: object
                    label: Content Section
                    fields:
                      - widget: string
                        name: section_id
                        label: Element ID
                        required: false
                      - widget: string
                        name: title
                        label: Title
                        required: false
                        hint: The title of the section.
                      - widget: hidden
                        name: component
                        label: Component
                        required: true
                        default: ContentBlock
                      - widget: markdown
                        name: content
                        label: Content
                        required: false
                        hint: The text content of the section.
                      - widget: list
                        name: actions
                        label: Action Buttons
                        required: false
                        fields:
                          - widget: string
                            name: label
                            label: Label
                            required: true
                            hint: The text displayed inside the button.
                          - widget: string
                            name: url
                            label: Button URL
                            required: false
                      - widget: hidden
                        name: type
                        label: Reference Type Name
                        required: true
                        hint: >-
                          Name of the Stackbit object model, used by fields of type
                          reference
                        default: contentblock
              - name: zh
                widget: object
                label: English
                fields:
                  - widget: string
                    name: title
                    label: Title
                    required: true
                    hint: The title of the page.
                  - widget: list
                    name: sections
                    label: Sections
                    required: false
                    hint: Home page sections.
                    types:
                      - name: contentblock
                        widget: object
                        label: Content Section
                        fields:
                          - widget: string
                            name: section_id
                            label: Element ID
                            required: false
                          - widget: string
                            name: title
                            label: Title
                            required: false
                            hint: The title of the section.
                          - widget: hidden
                            name: component
                            label: Component
                            required: true
                            default: ContentBlock
                          - widget: markdown
                            name: content
                            label: Content
                            required: false
                            hint: The text content of the section.
                          - widget: list
                            name: actions
                            label: Action Buttons
                            required: false
                            fields:
                              - widget: string
                                name: label
                                label: Label
                                required: true
                                hint: The text displayed inside the button.
                              - widget: string
                                name: url
                                label: Button URL
                                required: false
                          - widget: hidden
                            name: type
                            label: Reference Type Name
                            required: true
                            hint: >-
                              Name of the Stackbit object model, used by fields of type
                              reference
                            default: contentblock
              - name: en
                widget: object
                label: English
                fields:
                  - widget: string
                    name: title
                    label: Title
                    required: true
                    hint: The title of the page.
                  - widget: list
                    name: sections
                    label: Sections
                    required: false
                    hint: Home page sections.
                    types:
                      - name: contentblock
                        widget: object
                        label: Content Section
                        fields:
                          - widget: string
                            name: section_id
                            label: Element ID
                            required: false
                          - widget: string
                            name: title
                            label: Title
                            required: false
                            hint: The title of the section.
                          - widget: hidden
                            name: component
                            label: Component
                            required: true
                            default: ContentBlock
                          - widget: markdown
                            name: content
                            label: Content
                            required: false
                            hint: The text content of the section.
                          - widget: list
                            name: actions
                            label: Action Buttons
                            required: false
                            fields:
                              - widget: string
                                name: label
                                label: Label
                                required: true
                                hint: The text displayed inside the button.
                              - widget: string
                                name: url
                                label: Button URL
                                required: false
                          - widget: hidden
                            name: type
                            label: Reference Type Name
                            required: true
                            hint: >-
                              Name of the Stackbit object model, used by fields of type
                              reference
                            default: contentblock
          - widget: hidden
            name: template
            label: Template
            required: true
            default: home
  - name: page
    label: Pages
    folder: src/pages/
    create: true
    extension: md
    slug: '{{slug}}'
    fields:
      - name: en
        widget: object
        label: English
        fields:
          - widget: string
            name: title
            label: Title
            required: true
            hint: The title of the page
          - widget: string
            name: subtitle
            label: Subtitle
            required: false
            hint: The text shown below the page title.
          - widget: image
            name: img_path
            label: Image
            required: false
            hint: The image shown below the page title.
      - name: zh
        widget: object
        label: Traditional Chinese
        fields:
          - widget: string
            name: title
            label: Title
            required: true
            hint: The title of the page
          - widget: string
            name: subtitle
            label: Subtitle
            required: false
            hint: The text shown below the page title.
          - widget: image
            name: img_path
            label: Image
            required: false
            hint: The image shown below the page title.
      - name: cn
        widget: object
        label: Simplified Chinese
        fields:
          - widget: string
            name: title
            label: Title
            required: true
            hint: The title of the page
          - widget: string
            name: subtitle
            label: Subtitle
            required: false
            hint: The text shown below the page title.
          - widget: image
            name: img_path
            label: Image
            required: false
            hint: The image shown below the page title.
      - widget: hidden
        name: template
        label: Template
        required: true
        default: page
      - widget: markdown
        name: body
        label: Content
        required: false
        hint: Page content
    filter:
      field: template
      value: page
